insert into main.Publisher (Publisher_No, Publisher_Name)
values  (1, 'Sybex'),
        (2, 'McGraw-Hill Osborne Media'),
        (3, 'John Wiley & Sons
'),
        (4, 'Morgan Kaufmann'),
        (5, 'Schmidt Ink'),
        (6, 'Addison-Wesley Pub Co'),
        (7, 'Macromedia Press'),
        (8, 'Wrox Press Inc'),
        (9, 'Berkley Pub Group'),
        (10, 'Penguin USA '),
        (11, 'O''Reilly & Associates'),
        (12, 'McGraw-Hill Trade'),
        (13, 'Picador'),
        (14, 'St. Martin''s Press'),
        (15, 'Crown Pub'),
        (16, 'Little Brown & Company'),
        (17, 'Simon & Schuster'),
        (18, 'HarperCollins'),
        (19, 'Jossey-Bass'),
        (20, 'Multnomah Publishers'),
        (21, 'Perennial'),
        (22, 'Dell Pub Co'),
        (23, 'Harlequin'),
        (24, 'Viking Press'),
        (25, 'Perseus Publishing'),
        (26, 'Random House'),
        (27, 'Knopf'),
        (28, 'Wolfram Media'),
        (29, 'Fireside'),
        (null, ''),
        (31, 'Random House Trade P'),
        (32, 'Gibbs Smith Publishe'),
        (33, 'Taunton Pr'),
        (34, 'Vendome Pr'),
        (35, 'Clarkson N. Potter'),
        (36, 'MIT Press'),
        (37, 'McGraw-Hill/Irwin'),
        (38, 'South-Western Colleg'),
        (39, 'Prentice Hall
'),
        (40, 'Warner Books'),
        (42, 'Pocket Books'),
        (43, 'Pantheon Books'),
        (44, 'Del Rey'),
        (45, 'Doubleday'),
        (46, 'St. Martin''s Press'),
        (47, 'Donald M. Grant Publ'),
        (48, 'Harvard Univ Pr
'),
        (49, 'Anchor Books'),
        (50, 'Harper'),
        (51, 'Harperperennial Library
'),
        (52, 'Harvest Books'),
        (53, 'Back Bay Books
'),
        (54, 'Ballantine Books
'),
        (55, 'Silhouette'),
        (56, 'W.W. Norton & Company'),
        (57, 'Putnam Pub Group'),
        (58, 'Scribner');